### ISSUE TITLE
Inclusão do campo de metadados no model Nfe

### ISSUE THREAD

**Issue by gabrielnaoto** [luispimenta/EnotasNfe#19]
Algumas prefeituras necessitam do endereço completo do local de prestação de serviço. Porém, no endpoint disponível da documentação os únicos campos aceitos são: 

```rb
nfe.servico = {
  ufPrestacaoServico: "PR",
  municipioPrestacaoServico: "Curitiba",
}
```

Porém, ao entrar em contato com o suporte do enotas, eles adicionaram um novo atributo para esses casos de prefeituras especiais, com a seguinte estrutura:

```json
"metadados": {
  "cidadeprestacao":{
    "municipio":"DIGITAR NOME MUNICÍPIO",
    "siglaUF":"SP",
    "logradouro":"DIGITAR NOME Rua",
    "numero":"S/N",
    "bairro":"DIGITAR NOME BAIRRO",
    "cep":"0000000"
  }
}
```

Abaixo exemplo testado pelo próprio enotas:

![image](https://user-images.githubusercontent.com/13211186/104258588-9c3f8680-545e-11eb-8b6a-55980595ca53.png)

![unnamed](https://user-images.githubusercontent.com/13211186/104258832-00624a80-545f-11eb-9f6a-ca466144d000.png)

**Comment by luispimenta** [comment]
Maravilha @gabrielnaoto !
