### ISSUE TITLE
Implementação do upload do certificado digital

### ISSUE THREAD

**Issue by marceloboth** [luispimenta/EnotasNfe#7]
@luispimenta precisamos fazer o upload do certificado digital, e notei que a gem ainda não suporta o upload. Olhei o seu código e vi que a gem está bem preparada para serializar em json e que teria que fazer uma mudança na classe connection para enviar o multipart do Faraday para a API do enotas. Vou implementar, mas antes gostaria de ver com você, se por acaso já não tem isso feito, ou se já pensou em como fazer. Você chegou a pensar como seria a melhor forma de fazer isso na gem?

**Comment by luispimenta** [comment]
eu fiz isso aqui localmente apenas pra subir um certificado :

require "faraday"
        Faraday.new do |conn|
          conn.request :multipart
          conn.adapter :net_http

          res = conn.post do |req|
            req.url "https://api.enotasgw.com.br/v2/empresas/#{workshop.token_enota}/certificadoDigital"
            req.headers['Authorization'] = 'Basic blablabla'
            req.headers['Accept'] = 'application/json'
            
            body = {}
            body['arquivo'] = Faraday::UploadIO.new(certificado.tempfile, 'application/x-pkcs12')
            body['senha'] = senha

            req.body = body
          end
          puts res.body      
        end

Se vc quiser, pode implementar sim, já daria um adianto bom :)

**Comment by marceloboth** [comment]
@luispimenta ótimo, acho que consigo fazer algo com esse código ai.
